### ISSUE TITLE
Boolean datatype

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#148]
Implement traits for Datatype creation for bool

**Comment by eugenwintersberger** [comment]
And here it is :D. I was actually waiting for this. The problem here is that there is no bool type in HDF5 if I recall correctly. Which also would not make too much sense because there is none in C. However, the situation is more complex in C++. Though, there is bool type in C++ std::vector<bool> for instance does not behave like any other vector. It is a specialization of std::vector with no data() method. 

So when it comes to bool we have to, and the same will be true for string, provide our own support types or let the user do all the hard work.

**Comment by martukas** [comment]
Yet, H5 has it defined [here](https://support.hdfgroup.org/HDF5/doc/RM/PredefDTypes.html)

**Comment by eugenwintersberger** [comment]
Yeah. There is a definition for a boolean datatype. And it would be absolutely no Problem how to deal with it. However, like with strings, it would take some additional effort to get a reasonable user experience.
