### ISSUE TITLE
Remove github pages

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#187]
Currently github packages just grows the size of the repository. This is really annoying. It takes ages to get a clone which is particularly bad for CI systems. We need to find a better solution for the documentation release.

**Comment by martukas** [comment]
Moving from gh-pages elsewhere turns out to be unnecessary. The snowballing of binary file history in the repository is avoidable. The key realization is this: history for the deployed docs page is unnecessary, as change history is kept for the source code. Therefore, every commit to the gh-pages branch must simply overwrite the previous page while mercilessly suppressing any attempt at history keeping. This is easily achieved with the following two changes:
``git commit --amend``, which overwrites the previous commit
``git push --force``, which then overwrites this commit in remote
The Jenkins pipeline script now does this for every commit to master. In addition, I have retroactively squashed all previous commits of gh-pages branch into one. So now cloning of repo is around 30 MB, an order of magnitude lower than before and, I think, acceptable.
