### ISSUE TITLE
Recursive create_dataset and create_group functions

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#199]
It might be nice to have recursive versions of these, akin to `node::get_node` for cases where you might have long paths and would prefer to have all the in-between nodes constructed implicitly

**Comment by eugenwintersberger** [comment]
Actually ou can already do this by setting the appropriate flag in the LinkCreationList. So there is basically nothing we have to do here. If we want to make things a bit more convenient we may should consider adding a special constructor where the configuration options are passed via flags rather than via property lists. However, that might be only applicable for boolean options. 

So for instance like this 

``` cpp
Dataset data(parent,'/measurement/sensors/temperature',type,dataspace,
                     DatasetConfig::WITH_INTERMEDIATE_GROUPS | 
                     DatasetConfig::COMPACT);
```

But how would be deal with options which require a more elaborate setup like chunks where we have to provide not only a layout flag but also chunk dimensions?

**Comment by eugenwintersberger** [comment]
Already covered by the LinkCreationList - we can close this.
