### ISSUE TITLE
A way to convert nullpadded Strings?

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#215]
Nullpadded strings are retrieved with all the dead weight. No combination of Datatype settings seems to do the conversion properly. Either
A) I'm not doing something right. Means we haven't come up with an obvious enough way to do it right.
B) Extra machinery is needed

**Comment by martukas** [comment]
This is particularly an issue if retrieving a `Simple`-sized dataset of fixed length strings. Of course you get all the padding. The easiest way to then trim them is to do `str = std::string(str.c_str())`.
I wonder if we could have some utilities for this. Or, for example, the opposite: I would like to give a function an `vector<string>` to an I/O function to write a dataset of fixed-length strings, although each element of the array may not have been presized to that length. Could some kind of automatic truncation.

**Comment by eugenwintersberger** [comment]
Strings are particularly complicated in HDF5. Currently our default setup is to use variable strings when std::string is used. I had in my original code some machinery to do the automatic conversion but in the end it turned out to be more complicated as the code made some assumptions which where not always correct. So for the case of fixed size strings I would rather leave it up to the user how to deal with the data retrieved. We could maybe provides some utility functions to deal with the retrieved data but I would not do that automatically during IO.

**Comment by eugenwintersberger** [comment]
I still do not thing that this is a good idea. I personally would suggest that people use something like the `trim` function from Boost's string algorithm package. The padding was deliberately chosen by the creator of a file and we simply do not know how to treat this. I may add some examples to show how to get rid of this padding stuff.

**Comment by eugenwintersberger** [comment]
Ok. One simple solution without external dependencies would be

``` cpp
buffer.erase(std::remove(buffer.begin(),buffer.end(),'\0'),buffer.end());
```

Added this to the `attribute_fixed_string_io.cpp` test source. Just to have an example.
