### ISSUE TITLE
read out integer value error in field

### ISSUE THREAD

**Issue by yuelongyu** [ess-dmsc/h5cpp#324]
```C++
    std::string bit_depth_readout_path = std::string(":NXentry/:NXinstrument/:NXdetector/bit_depth_readout"); // value of the field 4294967295
    nexus::DatasetList fields = nexus::get_objects(file.root(),
                                                   nexus::Path::from_string(bit_depth_readout_path));


    std::cout<<"datatype test uint:"<<H5Tequal(static_cast<hid_t>(fields[0].datatype()),H5T_NATIVE_UINT)<<std::endl; // return true
    std::cout<<"datatype test int:"<<H5Tequal(static_cast<hid_t>(fields[0].datatype()),H5T_NATIVE_INT)<<std::endl; // return false
    std::cout<<"bit_depth_readout:"<<fields[0].dataspace().size()<<std::endl;
    
    unsigned int bit_depth_readout; // unsigned
    fields[0].read(bit_depth_readout);
    std::cout<<"unsigned value:"<<bit_depth_readout<<std::endl; // return 4294967295 correct value

    int bit_depth_readout_wrong; // signed
    fields[0].read(bit_depth_readout_wrong);
    std::cout<<"signed value:"<<bit_depth_readout_wrong<<std::endl; // return 2147483647 wrong value. This should be -1 instead of maximum value of signed integer.
```
I have created a field with maximum unsigned 32bit int value (2^32-1 = 4294967295). When reading with signed int, the singed value is wrong, in principle signed integer should return -1 instead of 2147483647. Is there an easy way to get the exact data type of the field before reading the value instead of using H5Tequal to compare with all HDF5 native type?

**Comment by martukas** [comment]
Ok, I just had some time to think about this, and I am not sure why it should be the way you describe. Maybe if you C-style cast some data from a void pointer that's how it would be interpreted (though possibly depending on endianness, etc..). But here you are trying to read the data with the wrong type, so actually I'd expect some kind of error at best, because fundamentally this is undefined behavior. The value you get is either the result of static cast, or of however the HDF library defines such conversions. The C++ standard, for example says this about casts:
```
If the destination type is signed, the value is unchanged if it can be represented in the destination type (and bit-field width); otherwise, the value is implementation-defined.
```

**Comment by yuelongyu** [comment]
Thanks for your reply. I agree with you, it should be an datatype mismatch error in this case.

**Comment by eugenwintersberger** [comment]
We need to check application level.
