### ISSUE TITLE
No support for UTF8

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#360]
Contrary to `h5py` and old `libpniio` in `h5cpp` it is not possible to store strings in UTF8 format  i.e `CSET H5T_CSET_UTF8` .  Supported is only `CSET H5T_CSET_ASCII`, i.e. it is not possible to store characters which has more then 8bits.  Does it mean that all unicode string before writing should be encoded? 
But since we write it as `H5T_CSET_ASCII` how to recognize during the reading which one is UTF8 (and should be decoded) and which not?

If someone wants to use NeXus Format he/she should have full support for UTF8 strings, i.e. http://download.nexusformat.org/doc/html/datarules.html#nexus-data-types

**Comment by jkotan** [comment]
I there any way to distinguish between `CSET H5T_CSET_ASCII` and `CSET H5T_CSET_UTF8` when someone read the files, i.e. any `is_utf8()` method?

**Comment by eugenwintersberger** [comment]
Hi Jan. I am back from vacation. There is in principle no way to distinguish between an ASCII string and an UTF8 string from the structure of the byte array. I had a discussion with the HDF5 group today about this topic because I gave a talk about C++ and Unicode last time at the C++ user group in Hamburg. You must no in advance how the string you want to read is encoded (this is the reason for the encoding flag in the String data type). I am actually working a bit on this topic but it is rather hard to do as there is no native support for Unicode strings in C++ (one of the unfortunate downsides of the language). 

Concerning Nexus: in most cases the standard restricts you to the ASCII charset anyhow and thus the encoding does not matter. However, this is a good point and I strongly recommend that you may put this question on the agenda of one of the next Nexus meetings. At least I have now at least one user who requests Unicode support ;)

**Comment by eugenwintersberger** [comment]
Can be closed.
