### ISSUE TITLE
Use c++17 filesystem

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#368]
Looks like recent gcc and clang now have [c++17 support](https://en.cppreference.com/w/cpp/compiler_support), including [std::filesystem](https://en.cppreference.com/w/cpp/filesystem)

Can we free ourselves of boost now?

**Comment by martukas** [comment]
@amues @SkyToGround @eugenwintersberger thoughts on this?

**Comment by martukas** [comment]
This could at least be an optional thing. Or better yet, automatic based on detected support in compiler?

**Comment by jkotan** [comment]
If it is optional or automatic it is OK for me.

**Comment by matthew-d-jones** [comment]
`std::filesystem` is in the `experimental` namespace in gcc 8 and not present in the normal `std` namespace until gcc 9.

**Comment by eugenwintersberger** [comment]
I guess the major question is: what is the minimum gcc version we would like to support.

**Comment by SkyToGround** [comment]
One year later, I am still of the opinion that switching to `std::filesystem` is not an option yet. Even Centos 8 will only have GCC 8 it appears. It might be possible to have CMake select `std::filesystem` if it is available and the boost version if not. Implementing this might not be trivial though if there are large differences between the two interfaces.

**Comment by matthew-d-jones** [comment]
I agree dropping support for gcc 7 is not an option yet.
Interface is practically identical, mostly it would just be a case of `namespace fs = std::filesystem;` in place of the current `namespace fs = boost::filesystem;`.

**Comment by eugenwintersberger** [comment]
@SkyToGround @matthew-d-jones @jkotan  is there an estimate when the minimum gcc version can be pumped from 7 to 8?

**Comment by matthew-d-jones** [comment]
@eugenwintersberger We've switched to gcc 8 minimum everywhere in ESS codebases. The hold up now is our Mac Jenkins nodes because Apple Clang got `std::filesystem` support very late. We are waiting on replacement Mac hardware for the nodes so that the OS and thus Clang can be updated. I believe Tobias is reminding the relevant people that we are waiting for this, so hopefully it happens soon.

When this ticket can be implemented, this might be a useful resource: https://github.com/ess-dmsc/kafkacow/pull/109

**Comment by jkotan** [comment]
@eugenwintersberger at DESY we are still on mostly stretch (g++ 6.3)

**Comment by eugenwintersberger** [comment]
My point here is that C++17 introduces a lot of very useful features not only in the language but also in the standard library. With respect to h5cpp I consider for instance std::variant a very interesting option as a return value for path related commands where it would be otherwise difficult to deal with attributes and node instances.

However, since DESY is, as I expected still mostly on Debian Stretch and thus bound to gcc 6.3, we have to wait for their major upgrade anyhow.

**Comment by matthew-d-jones** [comment]
If you are particularly keen on having things like variant and optional then you could consider using these header-only libraries. They match the interface of the std library implementation so would be easy to replace when it is possible to move to C++17.
https://conan.io/center/variant-lite/1.2.2/?user=_&channel=_
https://conan.io/center/optional-lite/3.2.0/?user=_&channel=_
