### ISSUE TITLE
Not installing correctly on Mint 19

### ISSUE THREAD

**Issue by glicka** [ess-dmsc/h5cpp#381]
I tried following both the automatic instructions using conan and cmake, but neither one is installing correctly. Conan seems to work, but then when I try to import h5cpp.h in my code I get the error:
```
CMake Error at CMakeLists.txt:34 (find_package):
  By not providing "Findh5cpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "h5cpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "h5cpp" with any of
  the following names:

    h5cppConfig.cmake
    h5cpp-config.cmake

  Add the installation prefix of "h5cpp" to CMAKE_PREFIX_PATH or set
  "h5cpp_DIR" to a directory containing one of the above files.  If "h5cpp"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/glicka/GEANT/B4a/build/CMakeFiles/CMakeOutput.log".
```
And when I try to install h5cpp using cmake I get the error:
```
ERROR: boost_filesystem/1.65.1@bincrafters/stable: 'settings.compiler' value not defined
CMake Error at cmake/conan.cmake:322 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:399 (conan_cmake_install)
  CMakeLists.txt:21 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/glicka/h5cpp-0.1.0/build/CMakeFiles/CMakeOutput.log".
```
What do I need to do to get this to work?

**Comment by martukas** [comment]
Hi Adam,
Thanks for reporting this. So, first a disclaimer: we have not been testing this with Mint, so there may be some issues beyond my imagination at the moment. However, I suspect your issues are of a general nature.
Are you using conan for your own project? If so, you can try our conan package of h5cpp, so you don't have to explicitly build it and install it on your system.
Put this in your conan.txt file:
`h5cpp/0.1.0@ess-dmsc/testing`
Then, of course, you need some conan-related magic in your CMake file (see lines 13-35 in our CMakeLists.txt file). And you will also need to add our conan repo:
`conan remote add ess-dmsc https://api.bintray.com/conan/ess-dmsc/conan`
We now use conan for a alot of our projects and it is a cleaner way of managing dependencies, instead of installing everything to system dirs. This is especially useful if you are dealing with some libraries like ours that are in active development and you may have to update to new versions more frequently.

Also, in your second scenario, it actually looks like conan is still in play. This is probably because you forgot to do `-DCONAN=DISABLE` when running cmake.
 
Our readme probably needs updating. Sorry about that.

**Comment by eugenwintersberger** [comment]
I guess we can close this.
