### ISSUE TITLE
Keyword POSIX clashes

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#392]
driver.hpp does the following
```
enum class DriverID : unsigned {
  POSIX = 1,
  DIRECT = 2,
  MEMORY = 3,
  MPI    = 4
};
```

Unfortunately, something like `dlib` uses POSIX as a precompiler flag for some platform specific code options. While not totally our fault, we could easily side-step this by using different orthography. We should check the google style manual for how enums should be named.

**Comment by eugenwintersberger** [comment]
I had a look in the Google Style guide [here](https://google.github.io/styleguide/cppguide.html#Enumerator_Names) and if I understand Google correctly they want, in future, name enumerations like constants. This is not entirely wrong but, at least for me, somehow misses the point of an enumeration. 

So my suggestion would be leave our naming convention as it is and just change this one to something else (suggestions are welcome). Or use an entirely new scheme. I would suggest to do something like Google did with constants but instead of prefixing the values with `k` use and `e` instead to make clear that this is not a constant but an enumeration. In this case the above would read like this 

```cpp
enum class DriverID : unsigned { 
    ePosix = 1,
    eDirect =2,
    eMemory = 3,
    eMpi  = 4
};
```

Thou I do not like this approach too much it would have the advantage that this naming convention does not conflict with the one for macros too.

**Comment by knight-piggy** [comment]
So does this issue mean that the ess-dmsc/h5cpp could work with dlib? What about other matrix libraries like eigen3?
