### ISSUE TITLE
Consider adding getter for dimensions to Dataset

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/h5cpp#393]
It is possible to set dimensions directly on a dataset. However, getting the dimensions requires creating a temporary dataspace object, like this:
```cpp
auto dataset = group.get_dataset("dataset_name");
hdf5::dataspace::Simple dataspace(dataset.dataspace());
auto dims = dataspace.current_dimensions();
```

A getter for the dimensions directly on the dataset would be more intuitive:
```cpp
auto dataset = group.get_dataset("dataset_name");
auto dims = dataset.dimensions();
```

**Comment by eugenwintersberger** [comment]
Definitely a good point. It would be quite easy to implement such a member function. There are currently only two issues which I can think of
* the only reasonable values to return for such a method would be the current number of elements along each dimension
* which leads to the second problem: what would you return in case of a scalar dataset?

**Comment by eugenwintersberger** [comment]
Ok. Here is my solution to this issue. I extended the `Dataspace` base class with a `current_dimensions` method. This is now available for all dataspaces. In order to determine the current dimensions of an attribute or a dataset instance one can use

```cpp
dataset.dataspace().current_dimensions();
//or
attribute.dataspace().current_dimensions();
```
This still ensures that the user is aware of the fact that the dimensions are determined by the dataspace and that the dimensions are the *current* ones. I hope this is enough to solve this issue.

**Comment by matthew-d-jones** [comment]
This looks like a good solution to me. Thanks @eugenwintersberger
