### ISSUE TITLE
Fixing problems with the online documentation

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#400]
In some cases, doxygen does not render the documentation correctly. It is not clear whether this is a doxygen or a breathe issue. However, it needs to be fixed.

**Comment by zjttoefs** [comment]
Done when:

- [ ] rendering problems solved
- [ ] one release for master and stable available

**Comment by jkotan** [comment]
Since we've changed API for h5cpp with #521 it would be good to provide webpage documentation for different versions of h5cpp i.e. `v:stable`, `v:latest`, `v0.4.1`, `v0.3.3`.  
There is not so many good versioning extensions for sphinx. Therefore, I think it would be good to prepare a PR with a simple solution based on git branches, i.e. each version of documentation has a separate branch e.g. `docs_v0.4.1` , `docs_latest` or docs_stable`. 
This approach allows to fix serious documentation bugs after the h5cpp version release in the corresponding branch, i.e. pushing docs bug fixes to the docs branches causes update of h5cpp documentation for its particular version. 
For older documentation versions the docs branches can be removed.
