### ISSUE TITLE
std::complex datatype

### ISSUE THREAD

**Issue by sekoenig** [ess-dmsc/h5cpp#452]
I would like to add support for an std::complex<double> datatype.  I assume the best way to proceed with that would be to use the existing Compound class and add an approriate `class TypeTrait<std::complex<double>>`.  What exactly should go into that class, and what else would I need to define in addition?

**Comment by eugenwintersberger** [comment]
I think we had this discussion a long time ago. In principle there is nothing wrong with this. There are some data types we may should provide support for out of the box. If I recall correctly there is even an example of how to do this for `std::complex` in the tests and/or in the examples. However, I would consider moving these header files into a separate directory so that this stuff does not bleed in by default but rather can be included on demand by a user. What about creating a directory tree `support/stl` in the `src/h5cpp` directory where we put header files providing some default support for STL data types.

We could then later even add support for data types from other libraries by putting them into a `support/whateverlibrary` directory.

Concerning complex numbers. I would suggest using the same schema that is used by `h5py` so that files written by `h5cpp` can directly read from Python ;)

**Comment by sekoenig** [comment]
Oh, indeed it is in the examples, thanks!

In my opinion `std::complex` is close enough to a standard numerics type that I would argue it deserves the same status as Float.  What problem do you see in having it available by default? (NB: C99 introduced comples numbers as builtin type, C++ didn't need to because the STL is tightly coupled with the core language anyway these days.)

Definitely I agree it's good to make it compatible with h5py.

**Comment by sekoenig** [comment]
I am tentatively merging the code from `examples/complex.hpp` into `datatype/type_traits.hpp`.  In doing so, I would like to simplify it a bit by getting rid of the extra struct.  The C++ standard guarantees the memory layout of std::complex<T>, so I would say we can just rely on that.  Quoting from [https://en.cppreference.com/w/cpp/numeric/complex](url):

> [...]  Possible declarations for its non-static data members include:
> - an array of type value_type[2], with the first element holding the real component and the second element holding the imaginary component (e.g. Microsoft Visual Studio)
> - a single member of type value_type _Complex (encapsulating the corresponding C language complex number type) (e.g. GNU libstdc++);
> - two members of type value_type, with the same member access, holding the real and the imaginary components respectively (e.g. LLVM libc++). 

> **An implementation cannot declare additional non-static data members that would occupy storage disjoint from the real and imaginary components, and must ensure that the class template specialization does not contain any padding. The implementation must also ensure that optimizations to array access account for the possibility that a pointer to value_type may be aliasing a std::complex specialization or array thereof.** (emphasis mine)

**Comment by sekoenig** [comment]
I have created a pull request for my solution.  I verified that the `complex_io.cpp` example works fine with this and moreover that reading a complex dataset (created from `std::vector<std::complex<double>>` with `h5py` does the right thing.
