### ISSUE TITLE
node tests crash on startup 

### ISSUE THREAD

**Issue by planetmarshall** [ess-dmsc/h5cpp#522]
node tests crash on startup due to static initialization of objects wth invalid handles. See https://github.com/ess-dmsc/h5cpp/blob/5b7c5a1639a6179d18c15b57a924d50e87c41a58/test/node/virtual_dataset_test.cpp#L53

**Steps to reproduce**

Build and run `node_test`

**Expected results**

The tests run and pass

**Actual results**

The executable fails to startup with

```
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: H5P.c line 253 in H5Pcreate(): not a property list class
    major: Invalid arguments to routine
    minor: Inappropriate type
libc++abi: terminating with uncaught exception of type std::runtime_error: ObjectHandle: constructor failed, invalid hid=-1
```

**Comment by jkotan** [comment]
@planetmarshall,  I could not reproduce the problem. Where you get the issue i.e. on which system?

**Comment by planetmarshall** [comment]
Yes I can reproduce on some systems but not others. Let me try and reproduce it in a container and I'll get back to you.

**Comment by jkotan** [comment]
Thanks. Indeed, I can reproduce it . It is because 
```c++
  const static property::FileCreationList gfcpl;
  const static property::FileAccessList gfapl;
```
cannot be created before `kFileCreate` `kFileAccess`.  For similar reason to create `const static DatasetTransferList` I had to use directly `H5P_DATASET_XFER` at https://github.com/ess-dmsc/h5cpp/blob/93b742f9d0ac30534d4917a8634b065051fc5bf0/src/h5cpp/property/dataset_transfer.hpp#L89

I will create workaround for it.  Other option would be to make the 'k' Class variables static ones.

**Comment by jkotan** [comment]
As we discussed since this PR removes pkg-config support in the current state cannot be accepted
