### ISSUE TITLE
docs do not build

### ISSUE THREAD

**Issue by drsramd** [ess-dmsc/h5cpp#565]
cmake 22.3
gcc 9.3
linux 20.04
all deps satisfied

cmake does not build /doc

**Comment by jkotan** [comment]
Building docs is tricky because in order to do it we usually need to install  newer versions of `breathe` and `sphinx` that in the distribution. They contain necessary bug fixes. 
Currently, we use ubuntu 20.04 to build the docs, i.e.
https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fh5cpp/detail/master/348/pipeline/570
which gives us
https://ess-dmsc.github.io/h5cpp/latest/index.html
but we install breathe and sphinx with pip 
https://github.com/ess-dmsc/h5cpp/blob/955903b741c9b7e7608a9b1ea4f9ef31d81f8f21/Jenkinsfile#L188
On debian11 `make html` works with packages given it the distribution.

Could you show us the error you get when you build the documentation than we can help you more.

**Comment by drsramd** [comment]
Thank you very much; in my setup it had to be installed system wide as root, sudo make html had to be used output ended up in builld/Release/doc/build, system wide installation is still obsure to me ...
