### ISSUE TITLE
Drop Windows build node in ESS builds

### ISSUE THREAD

**Issue by amues** [ess-dmsc/h5cpp#570]
@eugenwintersberger @jkotan, as Windows builds are being added in GitHub CI as part of https://github.com/ess-dmsc/h5cpp/pull/501, we are evaluating the possibility dropping the Windows builds from the ESS Jenkins builds.

We don't use Windows internally, so we don't consider the effort it takes to maintain the Windows 10 build node is worth it, as that is the only Windows server we run in our CI infrastructure.

Do the new GitHub CI Windows builds cover the project's needs? What is your opinion on dropping the ESS Windows build?

**Comment by jkotan** [comment]
Hello @amues,
at DESY/PETRAIII  we try to avoid Windows but it is not always possible (because of vendor drivers). I think for us it is enough to it is enough to run Windows tests on github nodes and skip ESS Windows tests runs.
Then it would be good
1) to extend github tests to all branches (currently they are run only on master branches)
2) to fix the issue in #501 PR. Currently some windows tests are not launched
```
Run cd build
UpdateCTestConfiguration  from :D:/a/h5cpp/h5cpp/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/a/h5cpp/h5cpp/build/DartConfiguration.tcl
Test project D:/a/h5cpp/h5cpp/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
```
https://github.com/ess-dmsc/h5cpp/runs/4907883392?check_suite_focus=true
