### ISSUE TITLE
Float datatype has no Datatype constructor

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#79]
The `Float` datatype has no constructor creating an instance from a `Datatype` instance.

**Comment by eugenwintersberger** [comment]
There is some interesting aspect here. When constructing a `Float` from a `Datatype` instance (which is basically a copy construction) the corresponding constructor fails if `Datatype` instance was default constructed and thus is invalid. 
However, invalid types have a Class (which I find strange). So how do we deal with this? Does someone have a good idea?

**Comment by martukas** [comment]
The way I understand it is that you are not really supposed to construct datatypes with H5T_NO_CLASS, and it's only used as a return value for an invalid data type (invalid hid). At least that's what it looks like from the tests. So we could add a test for this value and throw exception instead of returning it, but then it sort of already has to be part of the enum, unless we want to design our own enum ab initio, without doing it with the underlying type? The we have more code to write. There is something to be said for scoped enum classes.
But the main question is maybe, what do you want a default constructor for a Float or Integer datatype to do?

**Comment by eugenwintersberger** [comment]
Actually I would expect that datatypes behave like all other objects in our library that they are invalid and thus all methods throw an exception when calling them (except `is_valid()`). 
At least I think that this is what I expect ;)
