### ISSUE TITLE
Tests as separate target

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#81]
Building unit tests should be a separate target from building the library, so that
A) The library can be built by the end user without unit tests
B) Building unit tests can be a separate step in Jenkins

**Comment by SkyToGround** [comment]
Well, the unit test executable is a separate target as it is now. Doing ``make unit_tests`` builds only that and its dependencies, in this case the h5cpp library.

However, when running ``make``/``make all`` the unit tests are being build by default which is maybe what you were thinking of changing?

**Comment by SkyToGround** [comment]
By the way, it is possible to build only the library by running ``make h5cpp_shared``.

**Comment by SkyToGround** [comment]
Martin, I will leave it up to you to close this issue if you feel it has been resolved.

**Comment by martukas** [comment]
Ok, well mostly... to summarize:
"make h5cpp_shared" makes only the h5cpp libraries
"make" or "make all" makes the h5cpp libraries + the test/examples
"make unit_tests" makes the h5cpp libraries + examples + all other tests
So, it's quite close, but still doesn't completely make sense. Why the examples by default?

**Comment by SkyToGround** [comment]
That is not entirely correct. ``make unit_tests`` builds _h5cpp_shared_ first as it is a dependency of _unit_tests_ and then it builds _unit_tests_.

The default when adding (non custom) targets in CMake is that they are being built when running ``make all``. To avoid this, add "EXCLUDE_FROM_ALL" to the target definition.

**Comment by martukas** [comment]
The first part of that makes sense. That's how I would expect it.
So I guess we just need to add this flag to the examples target and that should solve it.

**Comment by martukas** [comment]
And why "--gtest_filter=-ObjectId.*" ? This is messing up the reporting of test coverage for the ObjectId class.

**Comment by SkyToGround** [comment]
Thats a mistake by me. I don't remember putting it there but I must have done it when trying to figure out which tests were to blame for crashing the unit_tests executable.

**Comment by SkyToGround** [comment]
I removed the offending argument from the master branch.

**Comment by eugenwintersberger** [comment]
Good morning gentlemen. I am actually using now the code with tests removed from the `all` target and I have to admit that it is a bit annoying (the same is true for the examples). The major problem here is that I have to remember to build the tests whenever I am doing a rebuild (which is particularly annoying from within eclipse which provides a runner for tests and a parser for google test ;)). 

So here are my 50 cent to this issue

## Building without tests

This raises the simple question: who are our users? For a library, users are developers who want to write code. So, as a developer, if I build  a library (or any other dependency) for my software I definitely want to run the test to ensure that everything works fine on my platform and architecture. I do not see a good point why we would build without a tests. 

Concerning `jenkins`: why is it important that building the tests is a step of its own? Running the tests is basically the key thing to do in CI. 

So not building them would be rather strange, wouldn't it.

## The examples

I named the directory examples and currently the code there could be used as examples. However, on the long run this should be something like *system integration tests*. The idea is that aside from unit tests this directory contains code which tests how the different components of the library work together. I found it in my own projects rather helpful to see whether or not this stuff compiles (you cannot cover everything in the unit tests). 

Even if they would be mere examples it is good to have them built before shipping them to the user in order to ensure that they at least compile.

**Comment by SkyToGround** [comment]
I have no strong opinion either way. Thus I leave it to you two to fight it out. Tell me what you have decided on and I will be happy to make the appropriate changes.

With that in mind, I feel that there has been a few misunderstandings about how CMake targets work. Thus maybe it is a good idea to have a short Google Hangouts discussion on the subject?

I did some testing (HA!) and I am having trouble configuring CMake such that the tests are executed when running ``make test``. I have no good idea of why this is the case though I might look into it a bit later.

**Comment by eugenwintersberger** [comment]
Have seen that too. Though I have to admit that I did not go into the details of how the testbuild works. Will do this next week. I guess we also should structure the tests a bit better.

**Comment by martukas** [comment]
Fights are fun :)
Ok, building them and running them can be one step, and you are suggesting that this be done with "make test" ?
I think this very much depends on how you run everything. In my case, I run "make generate_coverage" which also creates the html version of coverage reports locally (which I asked Jonas to bring back) that I can look at without building on Jenkins. I'm not a coverage nut, nor am I even an adept re unit testing, but I find this useful, as it gives me some idea of whether the tests are actually doing what I think they are doing. It has helped me catch some edge cases recently in something as simple as ObjectId.
I don't know that I agree with you on compiling the tests for the end-user in general. You don't compile or look at or care about unit tests when you download boost, Qt or ROOT or whatever. Well, in it's current maturity, our library probably deserves to get interrogated as such on every system is compiled on, so ok, for now I agree it maybe ok to do this. So, I mean, we can make our users do this, but I very much doubt that they will consciously desire it :)

**Comment by SkyToGround** [comment]
By the way, one alternative is to build the tests only if the dependencies (Google Test) are available. Thus if the user does not have GTest the unit tests will not be built.

**Comment by eugenwintersberger** [comment]
It depends on how I download the package. When I install something from the package repository of my Linux distribution I do not run tests. But when I download a source package I virtually always run the tests after the build ;)

**Comment by martukas** [comment]
This now works as I described. I don't know if it was done in response to this or what, but I am now happy :)
