### ISSUE TITLE
CentOS build node

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#85]

**Comment by eugenwintersberger** [comment]
As far as I know there is virtually nothing available on CentOS by default (from the plain vanilla repositories). No HDF5 no googletest.

**Comment by amues** [comment]
We have google test installed from the EPEL repository, but it's a fairly old version (1.6.0).

**Comment by martukas** [comment]
@amues @eugenwintersberger 
This is now almost working, with containers no less!
Except two things:
* sphinx is missing for docs generation. Should it be procurable via conan? I guess it is only needed on fedora
* the conan package for zlib is not working. Not sure if that means we need a dmsc package for it or there is something relatively stupid I forgot to do to make it work. Can you take a look?
* is there any way to avoid building all of boost every time? It is taking a really long time, especially if we do multiple platforms for each step

**Comment by martukas** [comment]
And so, it looks like it's also run out of memory in the middle of a build... which may be a sign of yet bigger problems?

**Comment by eugenwintersberger** [comment]
I guess we can happily omit the documentation build on CentOS. If a developer really wants to do this it is his problem to get sphinx working. For us it is important that the code builds and passes all tests.

I guess it should be possible to restrict the conan build of the boost library for particular components. Though I would rather think about building a conan package of boost with CentOS and then upload the binary package to a conan server. 

If you are running this stuff in a container, is it possible that there is a limit for the memory consumption of a container? I had a similar issue with boost::spirit in another project where it was not possible to build the code on the build instances on Ubuntu Launchpad as spirit used more than 6GByte :)

**Comment by amues** [comment]
@martukas Do you refer to https://jenkins.esss.dk/dm/job/ess-dmsc/job/h5cpp/job/issue_85/19/ when you mention it might have run out of memory? I've just checked and the Jenkins slave had actually run out of disk space. I've cleaned the disk and updated the weekly Jenkins Docker clean-up job to remove old stopped containers besides the images.
I'll take a look into the zlib issue, as it works for software using HDF5, which also depends on it (at least on CentOS).
We do have a binary version of Boost cached in our local Conan server (for CentOS with GCC 4.8 and 6.3; I can add a Fedora build as well). The package is named Boost/1.65.1-dm1@ess-dmsc/stable; we created our own package because the existing one doesn't build on CentOS with GCC 4.8 – but our package doesn't have the options to select a subset of the components.

**Comment by amues** [comment]
@martukas Can you send me a reference to a build log where the problem with zlib occurs?

**Comment by amues** [comment]
@martukas I've added Fedora binaries to our local Conan server. When they finish compiling (see the current builds on Jenkins), please try to build the branch again. I also suggest you update the Jenkinsfile to use the latest versions of the containers:
```
essdmscdm/centos-build-node:0.8.0
essdmscdm/fedora-build-node:0.4.1
```
